name: Munch workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
     
      - name: Prettify frontend code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write "**/*.{js,md,ts,tsx}" --tab-width 2 --print-width 80 --single-quote true ---jsx-single-quote true --end-of-line lf
          only_changed: True
     
      - name: Prettify backend code
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./backend"
